; Imports
extern @assertFailed@8: proc
extern @doRectsOverlap@8: proc
extern @getCachedString@4: proc
extern @showErrorMessage@4: proc
extern _allocateMemory: proc
extern @loadSound@8: proc
extern _loadSoundFunc: proc
extern _timerUpdateFunc: proc
extern @formatElapsedTime@8: proc
extern @drawText@20: proc
extern @random@4: proc
extern _handleWindowSizeMessage: proc
extern @mainWindowPaint@4: proc
extern @updateActorSpriteRect@4: proc
extern _startGameTimer: proc
extern _togglePausedState: proc
extern _pauseGame: proc
extern @addActorOfType@8: proc
extern _getFreeActor: proc

; exports
; public _WinMain@16