EXTERN __imp__DeleteObject@4: far
EXTERN __imp__SelectObject@8: far
EXTERN __imp__GetTextExtentPoint32A@16: far
EXTERN __imp__BitBlt@36: far
EXTERN __imp__PatBlt@24: far
EXTERN __imp__CreateCompatibleBitmap@12: far
EXTERN __imp__TextOutA@20: far
EXTERN __imp__GetStockObject@4: far
EXTERN __imp__GetDeviceCaps@8: far
EXTERN __imp__GetObjectA@12: far
EXTERN __imp__DeleteDC@4: far
EXTERN __imp__CreateBitmap@20: far
EXTERN __imp__GetTextMetricsA@8: far
EXTERN __imp__CreateCompatibleDC@4: far
EXTERN __imp__FreeResource@4: far
EXTERN __imp__lstrlenA@4: far
EXTERN __imp__FreeLibrary@4: far
EXTERN __imp__FindResourceA@12: far
EXTERN __imp__LoadResource@8: far
EXTERN __imp__lstrcmpiA@8: far
EXTERN __imp__GetPrivateProfileStringA@24: far
EXTERN __imp__WritePrivateProfileStringA@16: far
EXTERN __imp__LockResource@4: far
EXTERN __imp__lstrcpyA@8: far
EXTERN __imp__LCMapStringA@24: far
EXTERN __imp__LoadLibraryA@4: far
EXTERN __imp__LCMapStringW@24: far
EXTERN __imp__HeapReAlloc@16: far
EXTERN __imp__GetProcAddress@8: far
EXTERN __imp__HeapAlloc@12: far
EXTERN __imp__GetOEMCP@0: far
EXTERN __imp__VirtualAlloc@16: far
EXTERN __imp__GetCPInfo@8: far
EXTERN __imp__GetStringTypeW@16: far
EXTERN __imp__GetACP@0: far
EXTERN __imp__MultiByteToWideChar@24: far
EXTERN __imp__WriteFile@20: far
EXTERN __imp__GetStringTypeA@20: far
EXTERN __imp__HeapFree@12: far
EXTERN __imp__VirtualFree@12: far
EXTERN __imp__RtlUnwind@16: far
EXTERN __imp__HeapDestroy@4: far
EXTERN __imp__GetFileType@4: far
EXTERN __imp__HeapCreate@12: far
EXTERN __imp__SetHandleCount@4: far
EXTERN __imp__GetEnvironmentStringsW@0: far
EXTERN __imp__GetStdHandle@4: far
EXTERN __imp__GetTickCount@0: far
EXTERN __imp__LocalAlloc@8: far
EXTERN __imp__GetModuleHandleA@4: far
EXTERN __imp__GetStartupInfoA@4: far
EXTERN __imp__WideCharToMultiByte@32: far
EXTERN __imp__FreeEnvironmentStringsW@4: far
EXTERN __imp__GetEnvironmentStrings@0: far
EXTERN __imp__GetModuleFileNameA@12: far
EXTERN __imp__UnhandledExceptionFilter@4: far
EXTERN __imp__FreeEnvironmentStringsA@4: far
EXTERN __imp__GetVersion@0: far
EXTERN __imp__GetCommandLineA@0: far
EXTERN __imp__GetCurrentProcess@0: far
EXTERN __imp__TerminateProcess@8: far
EXTERN __imp__ExitProcess@4: far
EXTERN __imp__CreateWindowExA@48: far
EXTERN __imp__RegisterClassA@4: far
EXTERN __imp__wsprintfA: far
EXTERN __imp__LoadStringA@16: far
EXTERN __imp__DestroyWindow@4: far
EXTERN __imp__MessageBoxA@16: far
EXTERN __imp__GetMessageA@16: far
EXTERN __imp__TranslateMessage@4: far
EXTERN __imp__DispatchMessageA@4: far
EXTERN __imp__ShowWindow@8: far
EXTERN __imp__SetTimer@16: far
EXTERN __imp__UpdateWindow@4: far
EXTERN __imp__FrameRect@12: far
EXTERN __imp__LoadCursorA@8: far
EXTERN __imp__FillRect@12: far
EXTERN __imp__MoveWindow@24: far
EXTERN __imp__BeginPaint@8: far
EXTERN __imp__LoadBitmapA@8: far
EXTERN __imp__EndPaint@8: far
EXTERN __imp__GetClientRect@8: far
EXTERN __imp__DefWindowProcA@16: far
EXTERN __imp__PostQuitMessage@4: far
EXTERN __imp__SetFocus@4: far
EXTERN __imp__InvalidateRect@12: far
EXTERN __imp__KillTimer@8: far
EXTERN __imp__SetWindowTextA@8: far
EXTERN __imp__FindWindowA@8: far
EXTERN __imp__GetDC@4: far
EXTERN __imp__ReleaseDC@8: far
EXTERN __imp__OpenIcon@4: far
EXTERN __imp__SetWindowPos@28: far
EXTERN __imp__IsIconic@4: far
EXTERN __imp__LoadIconA@8: far
EXTERN __imp__sndPlaySoundA@8: far
EXTERN C s_skiMain: far
EXTERN C s_skiStatus: far
EXTERN C unk_array_0040a1ac: far
EXTERN C DAT_0040a22c: far
EXTERN C DAT_0040a258: far
EXTERN C DAT_0040a25c: far
EXTERN C DAT_0040a308: far
EXTERN C UINT_ARRAY_0040a434: far
EXTERN C DAT_0040a490: far
EXTERN C DAT_0040a4e0: far
EXTERN C DAT_0040a560: far
EXTERN C not_enough_space_for_arg_str: far
EXTERN C floating_point_not_loaded_str: far
EXTERN C microsoft_visual_str: far
EXTERN C s_runtime_error: far
EXTERN C DAT_0040a83c: far
EXTERN C s_program_name_unknown: far
EXTERN C DAT_0040a858: far
EXTERN C DAT_0040a85c: far
EXTERN C DAT_0040a860: far
EXTERN C s_GetLastActivePopup_0040a86c: far
EXTERN C s_GetActiveWindow_0040a880: far
EXTERN C s_MessageBoxA_0040a890: far
EXTERN C s_user32_dll: far
EXTERN C DAT_0040a8a8: far
EXTERN C DWORD_0040a8c0: far
EXTERN C DAT_0040c000: far
EXTERN C DAT_0040c004: far
EXTERN C DAT_0040c008: far
EXTERN C DAT_0040c010: far
EXTERN C DAT_0040c014: far
EXTERN C DAT_0040c018: far
EXTERN C DAT_0040c01c: far
EXTERN C DAT_0040c020: far
EXTERN C playerActorMaybe:Actor
EXTERN C entpack_ini_section_name_ski: far
EXTERN C s_entpack_ini: far
EXTERN C sourceFilename: far
EXTERN C s_Assertion_Failed_0040c0a8: far
EXTERN C s_assertErrorFormat: far
EXTERN C s_out_o_memory: far
EXTERN C iniSsConfigKey: far
EXTERN C DAT_0040c0dc: far
EXTERN C DAT_0040c0e0: far
EXTERN C stylePointsFormatString: far
EXTERN C DAT_0040c0ec: far
EXTERN C iniFsConfigKey: far
EXTERN C iniGsConfigKey: far
EXTERN C s_nosound_0040c0fc: far
EXTERN C s_insufficient_local_memory: far
EXTERN C s_iconSki_0040c120: far
EXTERN C s_WAVE: far
EXTERN C s_bitmap_load_error_message: far
EXTERN C DAT_0040c174: far
EXTERN C DAT_0040c182: far
EXTERN C DAT_0040c183: far
EXTERN C DAT_0040c390: far
EXTERN C DAT_0040c398: far
EXTERN C DAT_0040c39c: far
EXTERN C DAT_0040c3bc: far
EXTERN C DAT_0040c3c8: far
EXTERN C DAT_0040c408: far
EXTERN C DAT_0040c40c: far
EXTERN C DAT_0040c410: far
EXTERN C DAT_0040c414: far
EXTERN C DAT_0040c424: far
EXTERN C DAT_0040c428: far
EXTERN C DAT_0040c42c: far
EXTERN C DAT_0040c430: far
EXTERN C DAT_0040c438: far
EXTERN C ptr_floating_p_str: far
EXTERN C DAT_0040c440: far
EXTERN C PTR_s_not_enough_space_for_arg: far
EXTERN C DAT_0040c4d4: far
EXTERN C DAT_0040c4d8: far
EXTERN C DAT_0040c4dc: far
EXTERN C DAT_0040c4e0: far
EXTERN C DAT_0040c4e1: far
EXTERN C DAT_0040c4e2: far
EXTERN C DAT_0040c4e3: far
EXTERN C DAT_0040c4e8: far
EXTERN C DAT_0040c500: far
EXTERN C DAT_0040c5c0: far
EXTERN C sound_3:Sound
EXTERN C DAT_0040c5d8: far
EXTERN C statusWindowLastUpdateTime: far
EXTERN C DAT_0040c5e0: far
EXTERN C DAT_0040c5ec: far
EXTERN C SHORT_0040c5f0: far
EXTERN C DAT_0040c5f2: far
EXTERN C timerFrameDurationInMillis: far
EXTERN C sprites: far
EXTERN C skierScreenYOffset: far
EXTERN C DAT_0040c600: far
EXTERN C sound_8:Sound
EXTERN C redrawRequired: far
EXTERN C DAT_0040c614: far
EXTERN C actorListPtr: far
EXTERN C skiFreeHInstance: far
EXTERN C DAT_0040c620: far
EXTERN C hSkiStatusWnd: far
EXTERN C sound_6:Sound
EXTERN C DAT_0040c630: far
EXTERN C mainWindowDC: far
EXTERN C DAT_0040c640: far
EXTERN C DAT_0040c644: far
EXTERN C actors: far
EXTERN C PTR_0040c64c: far
EXTERN C DAT_0040c650: far
EXTERN C DAT_0040c658: far
EXTERN C statusWindowFont: far
EXTERN C textLineHeight: far
EXTERN C statusWindowHeight: far
EXTERN C statusWindowTotalTextWidth: far
EXTERN C statusWindowLabelWidth: far
EXTERN C DAT_0040c670: far
EXTERN C stringCache: far
EXTERN C updateTimerDurationMillis: far
EXTERN C inputEnabled: far
EXTERN C DAT_0040c680: far
EXTERN C DAT_0040c684: far
EXTERN C DAT_0040c688: far
EXTERN C DAT_0040c68c: far
EXTERN C DAT_0040c690: far
EXTERN C mainWndActivationFlags: far
EXTERN C currentTickCount: far
EXTERN C whiteBrush: far
EXTERN C SCREEN_WIDTH: far
EXTERN C DAT_0040c6a4: far
EXTERN C stylePoints: far
EXTERN C windowClientRect:tagRECT
EXTERN C sound_1:Sound
EXTERN C hSkiMainWnd: far
EXTERN C statusWindowDC: far
EXTERN C isPaused: far
EXTERN C DAT_0040c6d4: far
EXTERN C DAT_0040c6d8: far
EXTERN C sound_7:Sound
EXTERN C DAT_0040c6e8: far
EXTERN C DAT_0040c6ec: far
EXTERN C sound_9:Sound
EXTERN C DAT_0040c6f8: far
EXTERN C DAT_0040c6fc: far
EXTERN C prevMouseX: far
EXTERN C DAT_0040c702: far
EXTERN C skierScreenXOffset: far
EXTERN C prevTickCount: far
EXTERN C prevMouseY: far
EXTERN C DAT_0040c710: far
EXTERN C DAT_0040c714: far
EXTERN C sound_4:Sound
EXTERN C DAT_0040c720: far
EXTERN C playerActorPtrMaybe: far
EXTERN C DAT_0040c730: far
EXTERN C DAT_0040c738: far
EXTERN C DAT_0040c744: far
EXTERN C DAT_0040c748: far
EXTERN C SCREEN_HEIGHT: far
EXTERN C sound_5:Sound
EXTERN C PTR_0040c758: far
EXTERN C DAT_0040c75c: far
EXTERN C DAT_0040c760: far
EXTERN C sound_2:Sound
EXTERN C isMinimised: far
EXTERN C statusBorderRect: far
EXTERN C statusWindowNameStrPtr: far
EXTERN C DAT_0040c78c: far
EXTERN C sndPlaySoundAFuncPtr: far
EXTERN C isSoundDisabled: far
EXTERN C DAT_0040c7c0: far
EXTERN C DAT_0040c7c4: far
EXTERN C DAT_0040c7cc: far
EXTERN C DAT_0040c7dc: far
EXTERN C DAT_0040c7f0: far
EXTERN C DAT_0040c7f4: far
EXTERN C DAT_0040c8f8: far
EXTERN C DAT_0040c8fc: far
EXTERN C DAT_0040c900: far
EXTERN C DAT_0040c904: far
EXTERN C DAT_0040c908: far
EXTERN C DAT_0040c90c: far
EXTERN C DAT_0040c910: far
EXTERN C DAT_0040c91c: far
EXTERN C DAT_0040c92c: far
EXTERN C DAT_0040c934: far
EXTERN C DAT_0040c938: far
EXTERN C DAT_0040c93c: far
EXTERN C timerCallbackFuncPtr: far
EXTERN C elapsedTime: far
EXTERN C DAT_0040c948: far
EXTERN C DAT_0040c94c: far
EXTERN C DAT_0040c950: far
EXTERN C isFsGameMode: far
EXTERN C isGsGameMode: far
EXTERN C isSsGameMode: far
EXTERN C DAT_0040c960: far
EXTERN C DAT_0040c964: far
EXTERN C DAT_0040c968: far
EXTERN C DAT_0040c990: far
EXTERN C DAT_0040c994: far
EXTERN C DAT_0040c998: far
EXTERN C DAT_0040c9a0: far
EXTERN C DAT_0040cb47: far
EXTERN C DAT_0040cb48: far
EXTERN C DAT_0040cbc0: far
EXTERN C DAT_0040cbc4: far
EXTERN C DAT_0040ccc0: far
EXTERN C DAT_0040ccc4: far
EXTERN C DAT_0040cccc: far
EXTERN C DAT_0040ccd0: far
EXTERN C DAT_0040ccd4: far
